### PR TITLE
Removed rnpm commands for RN > 0.60.0 compatibility

### PR DESCRIPTION
**Pull request by smcelhinney**
Updating to use `react-native.config.js` as per https://github.com/react-native-community/cli/blob/master/docs/configuration.md

### CODE REVIEW

**Comment by jonstuebe** [comment]
Looks like this is all that's needed to fix the `rnpm` deprecation warning. Any chance this can get merged and published?

**Comment by mr-moon** [comment]
I would second this to be merged, as it prevents App Store submission.

**Comment by Jason-Cooke** [comment]
@rhdeck can this be merged?

**Comment by irodeanu** [comment]
Pls merge

**Comment by bradfx** [comment]
@rhdeck Can you please review? Thank you

**Comment by cwilby** [comment]
@rhdeck Another hand raised for merging this, seconding for App Store submission.

**Comment by smcelhinney** [comment]
Closing this PR as it's fixed in https://github.com/rhdeck/react-native-swift/commit/d674843d553f474c8843465574d21ac83db23284

**Pull request closed without merging**
